name    'scala'
version '0.1.0'
source 'https://github.com/haritzmedina/puppet-scala'
author 'Haritz Medina'
license 'Apache License, Version 2.0'
summary 'Module for installing scala from tarball'
description 'Module for installing scala from tarball'
project_page 'https://github.com/haritzmedina/puppet-scala'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'maestrodev/wget'
